config/routes.rb
Rails.application.routes.draw do
  resources :questions
  resources :members
  resources :events
  resources :news
  resources :companies
  resources :applicants
  root to: 'visitors#index'
  devise_for :users#, controllers: { registrations: "registrations"}
  resources :users
  
  
  get 'matching_system' => 'companies#matchpg'
  
end

app/models/event.rb
class Event < ActiveRecord::Base
  
  has_attached_file :picture, styles: { medium: "300x300>", thumb: "100x100>" }
  validates_attachment_content_type :picture, content_type: /\Aimage\/.*\Z/
  
  default_scope { order("created_at DESC") }
  
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:show, :edit, :update, :destroy]
  before_filter :admin_only, :except => [:index]
  

  # GET /events
  # GET /events.json
  def index
    @events = Event.all
  end

  # GET /events/1
  # GET /events/1.json
  def show
  end

  # GET /events/new
  def new
    @event = Event.new
  end

  # GET /events/1/edit
  def edit
  end

  # POST /events
  # POST /events.json
  def create
    @event = Event.new(event_params)

    respond_to do |format|
      if @event.save
        format.html { redirect_to @event, notice: 'تم إنشاء الفعالية الجديدة بنجاح' }
        format.json { render :show, status: :created, location: @event }
      else
        format.html { render :new }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1
  # PATCH/PUT /events/1.json
  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to @event, notice: 'تم تحديث الفعالية بنجاح' }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to events_url, notice: 'تم مسح الفعالية بنجاح' }
      format.json { head :no_content }
    end
  end

  private
  
  # this below code for checking if logged in user is the admin!
    def admin_only
     unless current_user.admin?
       redirect_to :back, :alert => "لا يمكن الدخول لهذه الصفحة"
     end
   end
  
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def event_params
      params.require(:event).permit(:name, :description, :picture, :place, :datefrom, :dateto, :time)
    end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_form.html.erb
<%= form_for @event, html: {multipart: true}  do |f| %>
  <% if @event.errors.full_messages.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
      <% @event.errors.full_messages.each do |message| %>
        <li><%= message if @event.errors.full_messages.first == message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
    
  <hr>  
  <br>


  <div class="field fonty formpad">
    <%= f.label :name, "اسم الفعالية" %><br>
    <%= f.text_field :name, :required=> true %>
  </div>
  <div class="field fonty formpad">
    <%= f.label :description, "وصف الفعالية" %><br>
    <%= f.text_area :description, :required=> true %>
  </div>
  <div class="field fonty formpad">
    <%= f.label :picture, "الصورة" %><br>
    <%= f.file_field :picture %>
  </div>
  <div class="field fonty formpad">
    <%= f.label :place, "المكان" %><br>
    <%= f.text_field :place, :required=> true %>
  </div>
  <br>
  
	<h4 class="field fonty formpad">
	 التاريخ والوقت 
	
	</h4>
  
  <div class="field fonty formpad">
    <%= f.label :datefrom, "من" %><br>
    <%= f.date_select :datefrom, :required=> true %>
  </div>
  <div class="field fonty formpad">
    <%= f.label :dateto, "إلى" %><br>
    <%= f.date_select :dateto, :required=> true %>
  </div>
  <div class="field fonty formpad">
    <%= f.label :time, "الوقت" %><br>
    <%= f.time_select :time, :required=> true %>
  </div>
  <div class="actions fonty formpad">
   <%= f.submit "حفظ" %> 
  </div>
<% end %>

app/views/events/edit.html.erb
</br>
</br>

<h1  class="fonty" align="center">تعديل الفعالية</h1>

<%= render 'form' %>


<br>
<br>
<p class="fonty floatR" >

<%= link_to 'عرض', @event %> |
<%= link_to 'الرجوع', event_path %>
</p>

app/views/events/index.html.erb
<br>
<br>
<br>
<h2 class="fonty" align="center">الفعاليات</h2>
<br>
<br>



    <% @events.each do |event| %>

 	<%= image_tag event.picture.url , width: '25%', align:'right'%>
		
	<br>
	<br>
	<div class="event">
	
	<h4 class="eventheading">
		اسم الفعالية:
			<%= event.name %> </h4>
			
	<h5 class="eventheading">
		الموقع:
			<%= event.place %> </h5>
		
	<h5 class="eventheading">
		من
			<%= event.datefrom %> 
			
		إلى
			<%= event.dateto %> </h5>
			
	<h5 class="eventheading">
		الوقت:
			<%= event.time.strftime("%H:%M") %> </h5>
		
		
	<p class="fonty">

			<%= event.description %>
	<br>
	<br>
	<br>
		
<h5 class="eventheading">
<p class="fonty floatR" >
<%= link_to 'سجل للفعالية', page_path('eventR') %>
</p>
</h5>

	<br>		
	<br>
	<br>

	<% if user_signed_in? %>
	
	<p class="fonty" align="left">
	<%= link_to 'عرض', event %>

	<%= link_to 'تعديل', edit_event_path(event) %>

	<%= link_to 'مسح', event, method: :delete, data: { confirm: 'هل أنت متأكد؟' } %>
	</p>
	<% end %>

	<br>
	
	<br>
	</p>

	<br>
	<br>
	<hr>
	<br>
	<br>
	<br> 
	</div>

	   <% end %>




	<br>
	<% if user_signed_in? %>
	<%= link_to 'ادخال فعالية جديد', new_event_path, class:'fonty floatR'%>
	<% end %>
		

app/views/events/new.html.erb
</br>
</br>

<h2 class="fonty" align="center">الفعالية الجديدة</h2>
<%= render 'form' %>

<h5 class="fonty" align="right">
<%= link_to 'الرجوع', events_path %>
</h5>

app/views/events/show.html.erb
<br>
<br>
<br>
<br>
<br>

<p class="fonty">
  <strong> اسم الفعالية</strong>
  <%= @event.name %>
</p>

<p class="fonty">
  <strong>وصف الفعالية</strong>
  <%= @event.description %>
</p>

<p class="fonty">
  <strong>الصورة</strong>
  <%= image_tag @event.picture %>
</p>

<p class="fonty">
  <strong>المكان</strong>
  <%= @event.place %>
</p>

<p class="fonty">
  <strong>التاريخ من</strong>
  <%= @event.datefrom %>
</p>

<p class="fonty">
  <strong>التاريخ إلى</strong>
  <%= @event.dateto %>
</p>

<p class="fonty">
  <strong>الوقت</strong>
  <%= @event.time.strftime("%H:%M") %>
</p>

<br>
<p class="fonty">
<%= link_to 'تعديل', edit_event_path(@event) %> |
<%= link_to 'الرجوع', events_path %>
</p>