config/routes.rb
Rails.application.routes.draw do
  resources :questions
  resources :members
  resources :events
  resources :news
  resources :companies
  resources :applicants
  root to: 'visitors#index'
  devise_for :users#, controllers: { registrations: "registrations"}
  resources :users
  
  
  get 'matching_system' => 'companies#matchpg'
  
end

app/models/news.rb
class News < ActiveRecord::Base

  has_attached_file :picture, styles: { medium: "300x300>", thumb: "100x100>" }
  validates_attachment_content_type :picture, content_type: /\Aimage\/.*\Z/
  
  default_scope { order("created_at DESC") }

end

app/controllers/news_controller.rb
class NewsController < ApplicationController
  before_action :set_news, only: [:show, :edit, :update, :destroy]
  #before_action :authenticate_user!, :except => [:create, :new]
  before_filter :admin_only, :except => [:index]
  

  # GET /news
  # GET /news.json
  def index
    @news = News.all
  end

  # GET /news/1
  # GET /news/1.json
  def show
  end

  # GET /news/new
  def new
    @news = News.new
  end

  # GET /news/1/edit
  def edit
  end

  # POST /news
  # POST /news.json
  def create
    @news = News.new(news_params)

    respond_to do |format|
      if @news.save
        format.html { redirect_to @news, notice: 'تم إنشاء الخبر الجديد بنجاح' }
        format.json { render :show, status: :created, location: @news }
      else
        format.html { render :new }
        format.json { render json: @news.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /news/1
  # PATCH/PUT /news/1.json
  def update
    respond_to do |format|
      if @news.update(news_params)
        format.html { redirect_to @news, notice: 'تم تحديث الخبر بنجاح' }
        format.json { render :show, status: :ok, location: @news }
      else
        format.html { render :edit }
        format.json { render json: @news.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /news/1
  # DELETE /news/1.json
  def destroy
    @news.destroy
    respond_to do |format|
      format.html { redirect_to news_index_url, notice: 'تم مسح الخبر  بنجاح' }
      format.json { head :no_content }
    end
  end

  private
  
  # this below code for checking if logged in user is the admin!
    def admin_only
     unless current_user.admin?
       redirect_to :back, :alert => "لا يمكن الدخول لهذه الصفحة"
     end
   end
  
    # Use callbacks to share common setup or constraints between actions.
    def set_news
      @news = News.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def news_params
      params.require(:news).permit(:title, :picture, :body, :date)
    end
end

app/helpers/news_helper.rb
module NewsHelper
end

app/views/news/_form.html.erb
<%= form_for @news, html: {multipart: true} do |f| %>
  <% if @news.errors.full_messages.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@news.errors.count, "error") %> prohibited this news from being saved:</h2>

      <ul>
      <% @news.errors.full_messages.each do |message| %>
        <li><%= message if @news.errors.full_messages.first == message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  
<hr>  
<br>


  <div class="field fonty formpad">
    <%= f.label :title, "العنوان"  %><br>
    <%= f.text_field :title, :required=> true %>
  </div>
  <div class="field fonty formpad">
    <%= f.label :picture, "الصورة" %><br>
    <%= f.file_field :picture %>
  </div>
  <div class="field fonty formpad">
    <%= f.label :body, "المحتوى" %><br>
    <%= f.text_area :body, :required=> true %>
  </div>
  <div class="field fonty formpad">
    <%= f.label :date, "التاريخ" %><br>
    <%= f.date_select :date %>
  </div>
  <br>
  <div class="actions fonty formpad">
    <%= f.submit "حفظ" %>
  </div>
  <br>
<% end %>

app/views/news/edit.html.erb
<h1>تعديل الخبر</h1>

<%= render 'form' %>

<%= link_to 'عرض', @news %> |
<%= link_to 'الرجوع', news_index_path %>

app/views/news/index.html.erb
<br>
<br>
<br>

<h2 class="fonty" align="center">الأخبار</h2>
<br>
<br>

    <% @news.each do |news| %>

  <%= image_tag news.picture.url , width: '25%', align:'right'%>
<br>
<br>
<div class="event">
 
<h4 class="eventheading">
<%= news.title %> </h4>
 
<h4 class="eventheading">
<%= news.date %> </h4>
 
<p class="fonty">

<%= news.body %>
<br>
<p class="fonty" align="left">
<br>
<% if user_signed_in? %>
<%= link_to 'عرض', news %>

<%= link_to 'تعديل', edit_news_path(news) %>

<%= link_to 'مسح', news, method: :delete, data: { confirm: 'هل أنت متأكد؟' } %>
<% end %>

<br>
</p>
<br>
</p>

<br>
<br>
<hr>
<br>
<br>
<br> 
</div>

   <% end %>




<br>
<% if user_signed_in? %>
<%= link_to 'ادخال خبر جديد', new_news_path, class:'fonty floatR'%>
<% end %>

app/views/news/new.html.erb
</br>
</br>

<h2 class="fonty" align="center">الخبر الجديد</h2>
<%= render 'form' %>

<h5 class="fonty" align="right">
<%= link_to 'الرجوع', news_index_path %>
</h5>

app/views/news/show.html.erb
<br>
<br>
<br>
<br>
<br>
<p class="fonty">
  <strong >العنوان:</strong>
  <%= @news.title %>
</p>

<p class="fonty">
  <strong>الصورة</strong>
  <%= image_tag @news.picture.url %>
</p>

<p class="fonty">
  <strong>المحتوى</strong>
  <%= @news.body %>
</p>

<p class="fonty">
  <strong>التاريخ</strong>
  <%= @news.date %>
</p>

<br>
<p class="fonty">
<%= link_to 'تعديل', edit_news_path(@news) %> |
<%= link_to 'الرجوع', news_index_path %>
</p>