config/routes.rb
Rails.application.routes.draw do
  resources :questions
  resources :members
  resources :events
  resources :news
  resources :companies
  resources :applicants
  root to: 'visitors#index'
  devise_for :users#, controllers: { registrations: "registrations"}
  resources :users
  
  
  get 'matching_system' => 'companies#matchpg'
  
end

app/models/company.rb
class Company < ActiveRecord::Base
  
  def self.search(search)
  		if search
  			where('companyName LIKE ? or jobTitle LIKE ? or nationality LIKE ? or gender LIKE ? 
  				or age LIKE ? or disability LIKE ? or education LIKE ?', "%#{search}%", "%#{search}%", "%#{search}%", "%#{search}%", "%#{search}%", "%#{search}%", "%#{search}%")
  		else
  			all
  		end
  	end
    
    
    before_save do
      self.disability.gsub!(/[\[\]\"]/, "") if attribute_present?("disability")
    end
  
  
  belongs_to :country
  
  
  GENDER_LISTComp = ["لا يهم", "أنثى", "ذكر"]
  EDUCATION_LIST = ["لا يهم","إبتدائي","إعدادي","ثانوي","جامعي"]
  
  
  def self.matching(iddd)
    where("company.id LIKE ?", "%#{iddd}" )
  end
  
  
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  before_action :set_company, only: [:show, :edit, :update, :destroy, :matchpg]
  before_action :authenticate_user!, :except => [:create, :new]
  before_filter :admin_only, :except => [:create, :new]
  

  # GET /companies
  # GET /companies.json
  def index
    @companies = Company.search(params[:search])
  end
  
  
  def matchpg
    @applicants= Applicant.all
    @companies = Company.matching(params[:id])
  end
  

  # GET /companies/1
  # GET /companies/1.json
  def show
  end

  # GET /companies/new
  def new
    @company = Company.new
  end

  # GET /companies/1/edit
  def edit
  end

  # POST /companies
  # POST /companies.json
  def create
    @company = Company.new(company_params)

    respond_to do |format|
      if @company.save
        format.html { redirect_to page_path('requestSaved'), notice: 'تم إدخال الطلب الجديد بنجاح' }
        format.json { render :show, status: :created, location: @company }
      else
        format.html { render :new }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /companies/1
  # PATCH/PUT /companies/1.json
  def update
    respond_to do |format|
      if @company.update(company_params)
        format.html { redirect_to @company, notice: 'تم تحديث الطلب بنجاح' }
        format.json { render :show, status: :ok, location: @company }
      else
        format.html { render :edit }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /companies/1
  # DELETE /companies/1.json
  def destroy
    @company.destroy
    respond_to do |format|
      format.html { redirect_to companies_url, notice: 'تم مسح الطلب بنجاح' }
      format.json { head :no_content }
    end
  end

  private
  
  # this below code for checking if logged in user is the admin!
    def admin_only
     unless current_user.admin?
       redirect_to :back, :alert => "لا يمكن الدخول لهذه الصفحة"
     end
   end
  
    # Use callbacks to share common setup or constraints between actions.
    def set_company
      @company = Company.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def company_params
      params.require(:company).permit(:noOfEmployees, :companyName, :jobTitle, :jobDescription, :contactPerson, :mobileNo, :email, :nationality, :gender, :age, :education,  disability:[])
    end
end

app/helpers/companies_helper.rb
module CompaniesHelper
  def checked(area)
    @company.disability.nil? ? false : @company.disability.match(area)
  end
end

app/views/companies/_form.html.erb
<%= form_for(@company) do |f| %>
  <% if @company.errors.any? %>
    <div id="error_explanation">
      <h2><%= @company.errors.count %> أخطاء منعت هذا الطلب من الحفظ</h2>

      <ul>
      <% @company.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<hr>  
<br>

  <div class="field fonty formpad">
<h3>
بيانات الوظيفة 
</h3>
  <br>
  </div>


<br/>
  <div class="field fonty formpad">
    <%= f.label :companyName, "اسم الشركة" %><br>
    <%= f.text_field :companyName, :required => true %>
  </div>
  <br/>
  
  <div class="field fonty formpad">
    <%= f.label :jobTitle, "اسم الوظيفة" %><br>
    <%= f.text_field :jobTitle, :required => true %>
  </div>
  <br/>
  
  <div class="field fonty formpad">
    <%= f.label :jobDescription, "تفاصيل الوظيفة" %><br>
    <%= f.text_area :jobDescription, :required => true %>
  </div>
  <br/>
  
  <div class="field fonty formpad">
    <%= f.label :noOfEmployees, "عدد الموظفين المطلوبين" %><br>
    <%= f.number_field :noOfEmployees, :required => true %>
  </div>
  <br/>
  
  <div class="field fonty formpad">
    <%= f.label :contactPerson, "اسم مقدم الطلب" %><br>
    <%= f.text_field :contactPerson, :required => true %>
  </div>
  <br/>
  
  <div class="field fonty formpad">
    <%= f.label :mobileNo, "رقم التواصل" %><br>
    <%= f.text_field :mobileNo, :required => true %>
  </div>
  <br/>
  
  <div class="field fonty formpad">
    <%= f.label :email, "البريد الإلكتروني" %><br>
    <%= f.text_field :email,:required => true %>
  </div>
  
  <br/>
  
  <h3 class="field fonty formpad">
  مواصفات الموظف المطلوبة 
  </h3>
  <br/>
  
  <div class="field fonty formpad">
    <%= f.label :nationality, "الجنسية" %><br>
    <%= f.collection_select :nationality, Country.all, :name, :name, :required => true, :include_blank => true  %>
  </div>
  <br/>
  
  <div class="field fonty formpad">
    <%= f.label :gender, "الجنس" %><br>
    <%= f.select(:gender, Company::GENDER_LISTComp,:required => true)  %>
  </div>
  <br/>
  
  <div class="field fonty formpad">
    <%= f.label :age, "متوسط العمر" %><br>
    <%= f.number_field :age %>
  </div>
  <br/>
  
  <div class="field fonty formpad">
      <%= f.label :disability, "نوع الإعاقة" %> <br> <br>
	  
     <%= check_box_tag 'company[disability][]', 'سمعية', checked('سمعية'), id: 'disability_hear' %>  
 	  <%= label_tag 'disability_hear', 'سمعية'%><br>
	 
    <%= check_box_tag 'company[disability][]', 'بصرية', checked('بصرية'), id: 'disability_vision' %> 
	 <%= label_tag 'disability_vision', 'بصرية'%> <br>
	
    <%= check_box_tag 'company[disability][]', 'حركية', checked('حركية'), id: 'disability_move' %> 
	  <%= label_tag 'disability_move', 'حركية'%><br>
	  
    <%= check_box_tag 'company[disability][]', 'ذهنية', checked('ذهنية'), id: 'disability_brain' %>
	  <%= label_tag 'disability_brain', 'ذهنية'%> <br>

    <%= check_box_tag 'company[disability][]', 'لا يهم', checked('لا يهم'), id: 'disability_no', :checked => true %>
	  <%= label_tag 'disability_no', 'لا يهم'%> <br>
	
	
  </div>
  
  <br/>
  
  <div class="field fonty formpad">
    <%= f.label :education, "المستوى التعليمي" %><br>
    <%= f.select(:education,Company::EDUCATION_LIST, :required => true) %>
  </div>
  <br/>
  
  <div class="actions fonty formpad">
    <%= f.submit "حفظ" %>
  </div>
<% end %>

app/views/companies/edit.html.erb
<br>
<br>
<br>
<h1 class="fonty" align="center">تعديل بيانات المؤسسة</h1>
<%= render 'form' %>



<br>
<br>
<p class="fonty floatR" >
<%= link_to 'عرض', @company %> |
<%= link_to 'رجوع', companies_path %>
</p>

app/views/companies/index.html.erb
<br>
<br>
<br>

<h2 class="fonty" align="center">قائمة المؤسسات</h2>
<br>
<br>
<table class="fonty table" align="center">
    <thead>
		 <tr>
			 <th class="tablespace eventheading down righttext" colspan="3">بيانات الوظيفة</th>
			 <th class="tablespace eventheading down righttext" colspan="9">مواصفات الموظف المطلوبة</th>
		 </tr>
    </thead>
	
  <thead>
    <tr>
		<div class="field fonty formpad">
		<%= form_tag companies_path, :method => 'get' do %>
		      <%= text_field_tag :search, params[:search] %>
		     <%= submit_tag "بحث" %>
		      <% end %>
		  	</div>
			  
			  <br>
		
      <th class="tablespace eventheading down"> اسم المؤسسة </th>
      <th class="tablespace eventheading down">اسم الوظيفة</th>
      <th class="tablespace eventheading down">عدد الوظائف</th>
    <%#  <th>تفاصيل الوظيفة</th> %>
    <%#  <th>اسم مقدم الطلب</th> %>
    <%#  <th>رقم التواصل</th> %>
    <%#  <th>البريد الإلكتروني</th> %>
      <th class="tablespace eventheading down">الجنسية</th>
      <th class="tablespace eventheading down">الجنس</th>
      <th class="tablespace eventheading down">متوسط العمر</th>
      <th class="tablespace eventheading down">الإعاقة</th>
      <th class="tablespace eventheading down">المستوى التعليمي</th>
      <th colspan="4"></th>
    </tr>
  </thead>

  <tbody>
    <% @companies.each do |company| %>
      <tr>
        <td class="tablespace fonty"><%= company.companyName %></td>
        <td class="tablespace fonty"><%= company.jobTitle %></td>
        <td class="tablespace fonty"><%= company.noOfEmployees %></td>
      <%#  <td><%= company.jobDescription %></td>
      <%#  <td><%= company.contactPerson %></td>
      <%#  <td><%= company.mobileNo %></td>
      <%#  <td><%= company.email %></td>
        <td class="tablespace fonty"><%= company.nationality %></td>
        <td class="tablespace fonty"><%= company.gender %></td>
        <td class="tablespace fonty"><%= company.age %></td>
        <td class="tablespace fonty"><%= company.disability %></td>
        <td class="tablespace fonty"><%= company.education %></td>
        <td class="tablespace fonty"><%= link_to 'عرض', company %></td>
        <td class="tablespace fonty"><%= link_to 'تعديل', edit_company_path(company) %></td>
        <td class="tablespace fonty"><%= link_to 'مسح', company, method: :delete, data: { confirm: 'هل أنت متأكد؟' } %></td>
		 <td class="tablespace fonty">  <button class="fonty"><%= link_to 'مطابقة', matching_system_path(:id => company.id) %></button> </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'ادخال شركة جديدة', new_company_path, class:'fonty floatR'%>

app/views/companies/matchpg.html.erb
<br>
<br>
<br>

<h2 class="fonty" align="center">صفحة المطابقة</h2>
<br>
<br>
<br>
<div class="formpad">
	<h4 class="eventheading"> الوظيفة </h4><br>

	<table class="fonty table" align="center">
	    <thead>
	 		<tr>
      <th class="tablespace eventheading down"> اسم المؤسسة </th>
      <th class="tablespace eventheading down">اسم الوظيفة</th>
      <th class="tablespace eventheading down">عدد الوظائف</th>
			 
			 </tr>
	    </thead>
		
        <tr>
        <td class="tablespace fonty"><%= @company.companyName %></td>
        <td class="tablespace fonty"><%= @company.jobTitle %></td>
        <td class="tablespace fonty"><%= @company.noOfEmployees %></td>
        </tr>
	</table>
	
	
	<br>
	<br>
	<br>
	
	
	<div class="formpad">
	<h4 class="eventheading"> المتقدمين المرشحين للوظيفة </h4>	<br>

		<table class="fonty table" align="center">
		    <thead>
		 		<tr>
      <th class="tablespace eventheading down">الاسم</th>
      <th class="tablespace eventheading down">الجنسية</th>
      <th class="tablespace eventheading down">العمر</th>
      <th class="tablespace eventheading down">الجنس</th>
      <th class="tablespace eventheading down">الحالة الإجتماعية</th>
      <th class="tablespace eventheading down">الجوال</th>
      <th class="tablespace eventheading down">المستوى التعليمي</th>	
	        <th colspan="2"> </th>		 
				 </tr>
		    </thead>
			
			<!-- create empty arrays. 
			x: to hold the list of attributes of preferences
			y: to hold the list of values of preferences
			idarray: to hold the ids of applicants who have the matching preferences
				
				exclude the (no preferences) from array x -->
		<% x= [] %>
		<% y= [] %>
		<% idarray= [] %>
		
		<% if @company.nationality != "" %>
		
		<% x= ["nationality"] %>
		<% y= [@company.nationality] %>
		
		<%end%>
		
		<% if @company.gender != "لا يهم" %>
		
		<% x+= ["gender"] %>
		<% y+= [@company.gender] %>
		
		<%end%>
		
		<% if @company.disability !=  "لا يهم"  %>
		
		<% x+= ["disability"] %>
		<% y+= [@company.disability] %>
		
		<%end%>
		
		<% if @company.education != "لا يهم" %>
		
		<% x+= ["education"] %>
		<% y+= [@company.education] %>
		
		<%end%>
		

		<!-- iterate over the applicants and check if their info matchs required preferences
			 	if yes, add their id to array y.
			applicantarray: to hold the subset of the prefered characteristics of an applicant, then
			it will compare theis subset to the preference if match, it will add the applicant to the new table  -->
			
			
	    <% @applicants.each do |applicant| %>
		<% applicantarray= [] %>
			<% x.each do |hanan| %>
				<% applicantarray+= [applicant[hanan]] %>
			<%end%>				
			<% if applicantarray.to_set.subset?(y.to_set)%>
				<% idarray+= [applicant.id] %>				
			
			<%end%>



		<% if idarray.include? (applicant.id) %>
		
	        <tr>
	        <td class="tablespace fonty"><%= applicant.name %></td>
	        <td class="tablespace fonty"><%= applicant.nationality %></td>
	        <td class="tablespace fonty"><%= Applicant.getage(applicant.dob) %></td>
	        <td class="tablespace fonty"><%= applicant.gender %></td>
	        <td class="tablespace fonty"><%= applicant.status %></td>
	        <td class="tablespace fonty"><%= applicant.mobileNo %></td>
	        <td class="tablespace fonty"><%= applicant.education %></td>
	        <td class="tablespace fonty"><%= link_to 'عرض', applicant %></td>
	        <td class="tablespace fonty"><%= link_to 'تعديل', edit_applicant_path(applicant) %></td>
	        </tr>
		<%end%>
		<%end%>
		
	


			
		</table>

app/views/companies/new.html.erb
</br>
</br></br>
</br></br>
</br></br>
</br>

<h2 class="fonty" align="center">استمارة عرض وظيفة شاغرة</h2>

<%= render 'form' %>


<!--
<%= link_to 'Back', companies_path %>
-->

app/views/companies/show.html.erb
<br>
<br>
<br>
<br>

<h2 class="fonty" align="center"> بيانات الوظيفة</h2>
<br>
<br>
<br>
<div class="formpad">
<p class="fonty">
  <strong >اسم المؤسسة:</strong>
  <%= @company.companyName %>
</p>
<br>
<p class="fonty">
  <strong>المسمى الوظيفي :</strong>
  <%= @company.jobTitle %>
</p>
<br>

<p class="fonty">
  <strong>تفاصيل الوظيفة:</strong>
  <%= @company.jobDescription %>
</p>
<br>

<p class="fonty">
  <strong>عدد الموظفين المطلوبين:</strong>
  <%= @company.noOfEmployees %>
</p>
<br>

<p class="fonty">
  <strong>اسم مقدم الطلب:</strong>
  <%= @company.contactPerson %>
</p>
<br>

<p class="fonty">
  <strong>رقم التواصل:</strong>
  <%= @company.mobileNo %>
</p>
<br>

<p class="fonty">
  <strong>البريد الالكتروني:</strong>
  <%= @company.email %>
</p>
<br>

<p class="fonty">
  <strong>الجنسية:</strong>
  <%= @company.nationality %>
</p>
<br>

<p class="fonty">
  <strong>الجنس:</strong>
  <%= @company.gender %>
</p>
<br>

<p class="fonty">
  <strong>متوسط العمر:</strong>
  <%= @company.age %>
</p>
<br>

<p class="fonty">
  <strong>نوع الإعاقة:</strong>
  <%= @company.disability %>
</p>
<br>

<p class="fonty">
  <strong>المستوى التعليمي:</strong>
  <%= @company.education %>
</p>
<br>
<br>
<p class="fonty floatR" >
<%= link_to 'تعديل', edit_company_path(@company)%> |
<%= link_to 'رجوع', companies_path %>
</p>


<button onclick="myFunction()" class="fonty">اطبع هذه الصفحة</button>

<script>
function myFunction() {
    window.print();
}
</script>


</div>