config/routes.rb
Rails.application.routes.draw do
  resources :questions
  resources :members
  resources :events
  resources :news
  resources :companies
  resources :applicants
  root to: 'visitors#index'
  devise_for :users#, controllers: { registrations: "registrations"}
  resources :users
  
  
  get 'matching_system' => 'companies#matchpg'
  
end

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 3.0 %>
<br><br>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div id= 'notice' class="alert alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true" align='left'>&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_nav_links_for_auth.html.erb
<% if user_signed_in? %>
 <!-- <li class="navbar navbar-right"><%= link_to 'تعديل الحساب', edit_user_registration_path %></li> -->

 <!--  <li class="navbar navbar-right"><%= link_to 'تسجيل الخروج', destroy_user_session_path, :method=>'delete' %></li> -->


	  
 	<li class="dropdown navbar fonty">
           <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"> الاعدادات  <span class="caret"></span></a>
		   <ul class="dropdown-menu">
		               <li align="center"><%= link_to 'تسجيل الخروج', destroy_user_session_path, :method=>'delete', :class=>'fonty' %></li>
					   <li role="separator" class="divider"></li>
		               <li align="center"><%= link_to 'تعديل الحساب', edit_user_registration_path(@user), :class=>'fonty' %></li>

		             </ul>
	   </li>

<% else %>

  <li class="navbar navbar-right"><%= link_to 'تسجيل الدخول', new_user_session_path %></li>
  <!-- ><li class="navbar navbar-right"><%= link_to 'التسجيل', new_user_registration_path %></li> -->
  
  
  
  <!-- SEARCH FEATURE
  <div class="col-sm-3 col-md-3 pull-left">
          <form class="navbar-form" role="search">
          <div class="input-group">
              <input type="text" class="form-control fonty" placeholder="بحث" name="srch-term" id="srch-term">
              <div class="input-group-btn">
                  <button class="btn btn-default" type="submit"><i class="glyphicon glyphicon-search"></i></button>
              </div>
          </div>
          </form>
          </div>
	  -->
  
<% end %>
<% if user_signed_in? %>
  <!-- ><li class="navbar navbar-right"><%= link_to 'Users', users_path %></li>-->
<% end %>

app/views/layouts/_navigation.html.erb
<%# navigation styled for Bootstrap 3.0 %>

<link href= "../../assets/stylesheets/1st_load_framework.css" rel= "stylesheet" type= "text/css" />



<!--  <h1 class="fonty" align="center" > اللجنة التطوعية لتوظيف ذوي الإعاقة</h1> TITLE -->
<!-- <hr> LINE?-->
<br>
<br>
<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container">
	  <br>
    <div class="navbar-header navbar-right">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
	  <!-- <img src="logo.jpg"  style="width:100%"> -->
      <%= link_to 'اللجنة التطوعية لتوظيف ذوي الإعاقة', root_path, class: 'navbar-brand larger' %>
    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav navbar-right" id="rtl">
        <%= render 'layouts/navigation_links' %>
      </ul>
	  <ul class="nav navbar-nav">
	  <%= render 'layouts/nav_links_for_auth' %>
  	 </ul>
    </div>
<!--	<hr> -->

  </div>
</nav>

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>






<li class="navbar"><%= link_to 'تواصل معنا', page_path('contact') %></li>
<% if user_signed_in? %>
 	<li class="dropdown navbar fonty">
           <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"> قاعدة البيانات <span class="caret"></span></a>
           <ul class="dropdown-menu">
             <li><a href="/applicants" class="fonty" align="center">ذوي الإعاقة</a></li>
             <li role="separator" class="divider"></li>
             <li><a href="/companies" class="fonty" align="center">المؤسسات</a></li>
           </ul>
	   </li>



<% else %>
 <li class="dropdown fonty">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">سجل الآن <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="/applicants/new" class="fonty" align="center">ذوي الإعاقة</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="/companies/new" class="fonty" align="center">المؤسسات</a></li>
          </ul>
        </li>
<% end %>


<!--  <li class="navbar"><%= link_to 'من نحن', page_path('about') %></li>  -->
<li class="navbar"><%= link_to 'معرض الصور', page_path('gallery') %></li>
<li class="navbar"><%= link_to 'الفعاليات القادمة', events_path %></li>
<li class="navbar"><%= link_to 'الأخبار', news_index_path %></li>



<li class="navbar"><%= link_to 'من نحن', members_path %></li>
<li class="navbar"><%= link_to 'الصفحة الرئيسية', root_path %></li>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "The Voluntry Committee for Recruiting People with Disability " %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Rails Devise" %>">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
	
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
	<%= javascript_include_tag 'jquery.cookie.js', 'data-turbolinks-track' => true %>
	<%= javascript_include_tag 'jquery.fontResize.js', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body >
    <header>
      <%= render 'layouts/navigation' %>
    </header>
    <main role="main">
       <%= render 'layouts/messages' %>
       <%= yield %>
    </main>





  </body>
</html>